server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/persones
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #todo
  database: postgresql
  database-platform: org.hibernate.dialog.PostgreSQLDialect
  show-sql: true
  properties:
    hibernate:
      format_sql: true




